#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/server/src/unittest/gpopt/translate/Makefile
#

subdir = src/backend/gporca/server/src/unittest/gpopt/translate
top_builddir = ../../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS=	CTranslatorDXLToExprTest.o \
	CTranslatorExprToDXLTest.o

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
