#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/server/src/unittest/gpopt/engine/Makefile
#

subdir = src/backend/gporca/server/src/unittest/gpopt/engine
top_builddir = ../../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS=	CBindingTest.o CEngineTest.o CEnumeratorTest.o

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
