#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/libgpos/server/src/unittest/Makefile
#

subdir = src/backend/gporca/libgpos/server/src/unittest
top_builddir = ../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

SUBDIRS = gpos

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
