#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/libgpos/server/src/unittest/gpos/io/Makefile
#

subdir = src/backend/gporca/libgpos/server/src/unittest/gpos/io
top_builddir = ../../../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS=	CFileTest.o COstreamBasicTest.o COstreamFileTest.o COstreamStringTest.o

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
