#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/libgpos/server/src/unittest/gpos/string/Makefile
#

subdir = src/backend/gporca/libgpos/server/src/unittest/gpos/string
top_builddir = ../../../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS=	CStringTest.o CWStringTest.o

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
