subdir=src/backend/access/gin
top_builddir=../../../../..

include $(top_builddir)/src/Makefile.global

TARGETS=ginpostinglist

include $(top_builddir)/src/backend/mock.mk

ginpostinglist.t: $(top_builddir)/src/backend/access/gin/ginpostinglist.o
