# Makefile for GPORCA unit test program
#
# src/backend/gporca/libgpos/server/Makefile
#

subdir = src/backend/gporca/libgpos/server
top_builddir = ../../../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS     = src

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
