#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/libgpos/server/src/unittest/gpos/Makefile
#

subdir = src/backend/gporca/libgpos/server/src/unittest/gpos
top_builddir = ../../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

SUBDIRS = common error io memory string task

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
