#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/server/src/startup/Makefile
#

subdir = src/backend/gporca/server/src/startup
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS=	main.o

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
