#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/server/src/unittest/dxl/base/Makefile
#

subdir = src/backend/gporca/server/src/unittest/dxl/base
top_builddir = ../../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS=	CDatumTest.o

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
