#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/libgpos/server/src/unittest/gpos/memory/Makefile
#

subdir = src/backend/gporca/libgpos/server/src/unittest/gpos/memory
top_builddir = ../../../../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

OBJS=	CCacheTest.o CMemoryPoolBasicTest.o

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
