#
# Makefile for GPORCA unit test program
#
# src/backend/gporca/libgpos/server/src/Makefile
#

subdir = src/backend/gporca/libgpos/server/src
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

include $(top_srcdir)/src/backend/gporca/gporca.mk

SUBDIRS     = unittest

include $(top_srcdir)/src/backend/gporca/server/gporca_test.mk
