#
# Makefile for optimizer
#
# src/backend/gporca/Makefile
#

subdir = src/backend/gporca
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

# server is not included here, see parent Makefile
SUBDIRS     = src

include $(top_srcdir)/src/backend/common.mk
